dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8
  - openjdk11
  - openjdk10
  - openjdk8
  - openjdk7
before_install:
  - sudo apt-get install -y openjfx
script:
  - ant all
email: false
